#!/bin/bash
# Example PBS submission script (edit the placeholders before use).

# ---- User settings (edit these) ----
WORK_DIR="/path/to/Outputs"           # Where input/output data files live
ENV_NAME="your_conda_env"             # Conda environment to activate

# IMPORTANT:
#   The compute_coeff*.py scripts expect r0_segment1.npy, r0_segment2.npy, ...
#   These are generated by running the corresponding cell in a_lm.ipynb.
#   JOB_COUNT should match the number of r0 segments you generated.
#   If you change the number of segments, update a_lm.ipynb to regenerate them.
JOB_COUNT=4                            # Number of jobs / script shards (match r0 segments)

# Optional: pin each job to a specific node (one node per job)
# Leave NODE_LIST empty if you do NOT want to force specific hosts.
NODE_LIST=(nodeA nodeB nodeC nodeD)    # e.g., (m33 m34 m37 m39)

NCPUS=56                               # CPU cores per job
WALLTIME="24:00:00"                   # Job walltime (HH:MM:SS)
QUEUE="your_queue"                    # Queue name (optional; leave empty to omit)

# ---- Derived paths ----
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
LOG_DIR="${WORK_DIR}/logs"

# Ensure log directory exists
mkdir -p "${LOG_DIR}"

# Submit PBS scripts
for i in $(seq 1 ${JOB_COUNT}); do
    # Pick a node for this job if NODE_LIST is provided
    NODE=""
    if [ ${#NODE_LIST[@]} -ge ${i} ]; then
        NODE="${NODE_LIST[$((i-1))]}"
    fi

    cat > "submit_job${i}.pbs" << EOF
#!/bin/bash
#PBS -N ULDM_coeff${i}
#PBS -l walltime=${WALLTIME}
#PBS -j oe
#PBS -o ${LOG_DIR}/ULDM_coeff${i}.log
EOF

    # Add resource line (optionally pin to a host)
    if [ -n "${NODE}" ]; then
        echo "#PBS -l select=1:ncpus=${NCPUS}:host=${NODE}" >> "submit_job${i}.pbs"
    else
        echo "#PBS -l select=1:ncpus=${NCPUS}" >> "submit_job${i}.pbs"
    fi

    # Add queue line only if QUEUE is set
    if [ -n "${QUEUE}" ]; then
        echo "#PBS -q ${QUEUE}" >> "submit_job${i}.pbs"
    fi

    cat >> "submit_job${i}.pbs" << EOF

cd "${WORK_DIR}"

# Load environment (edit if you use something other than conda)
source ~/.bashrc
if command -v conda >/dev/null 2>&1; then
    eval "\$(conda shell.bash hook)"
    conda activate "${ENV_NAME}"
fi

export PYTHONUNBUFFERED=1

# Run the script from SCRIPT_DIR while keeping WORK_DIR as the cwd
python3 -u "${SCRIPT_DIR}/compute_coeff${i}.py"

# Optional cleanup of generated compute scripts (only if they were generated from a template)
rm -f "${SCRIPT_DIR}/compute_coeff${i}.py"
EOF

    echo "Submitting job ${i}..."
    qsub "submit_job${i}.pbs"
    echo "Job ${i} submitted."
    rm -f "submit_job${i}.pbs"
done

echo "All jobs submitted."
